#!/bin/bash
# Download audio from a YouTube playlist.

MUSIC_DIR=$HOME/Music/
ARCHIVE_FILE=$MUSIC_DIR/music-playlist.txt
# Playlist needs to be unlisted to work correctly
PLAYLIST_LINK="PLAYLIST_LINK_HERE"

youtube-dl --extract-audio --download-archive $ARCHIVE_FILE --audio-format mp3 $PLAYLIST_LINK
